-- Startdaten: NACH schema.sql einmal ausführen.

-- Spitznamen-Grundstock
insert into nicknames (name, author) values
  ('Makrelenöhrchen', 'Dennis'),
  ('Gagafrosch', 'Dennis'),
  ('Schnecke', 'Dennis'),
  ('Schneckenbär', 'Dennis'),
  ('Schneckentiger', 'Dennis'),
  ('Schneckerich', 'Dennis'),
  ('Schnecki Zimtzucker', 'Dennis'),
  ('Schnecki Süßsauer', 'Dennis'),
  ('Fürst von Schneckerich', 'Dennis'),
  ('Kröti', 'Dennis'),
  ('Kröterich', 'Dennis'),
  ('Krötofferus', 'Dennis'),
  ('Elsbeth(i)', 'Dennis'),
  ('Elsbethbär', 'Dennis'),
  ('Eleonore', 'Dennis'),
  ('Elisabeth', 'Dennis'),
  ('Ellie Elsbethson', 'Dennis'),
  ('Mausebär', 'Dennis'),
  ('Ed von Schneck', 'Dennis'),
  ('Krötentiger', 'Dennis'),
  ('Troll', 'Dennis'),
  ('Schneckennudel', 'Dennis'),
  ('Babyratte', 'Dennis'),
  ('Trollnase', 'Dennis'),
  ('Krümelbärchen', 'Dennis'),
  ('Maus', 'Dennis'),
  ('Mauserich', 'Dennis'),
  ('Stinketroll', 'Dennis'),
  ('Torfnase', 'Dennis'),
  ('Supermaus', 'Dennis'),
  ('Zaubermaus', 'Dennis'),
  ('Made', 'Dennis'),
  ('Made im Speckmantel', 'Dennis'),
  ('Quatschbär', 'Dennis'),
  ('Wutz', 'Dennis'),
  ('Zuckermaus', 'Dennis'),
  ('Seehund', 'Dennis'),
  ('Seeigel', 'Dennis'),
  ('Wurst', 'Dennis'),
  ('Wiener Würstchen', 'Dennis'),
  ('Pockenschweinchen', 'Dennis'),
  ('winkelfreund', 'Dennis'),
  ('Winkelenthusiatin', 'Dennis'),
  ('Fauchi 3', 'Dennis'),
  ('Schnuffnase', 'Dennis'),
  ('Quatschkröte', 'Dennis'),
  ('Schneckerinchen', 'Dennis'),
  ('Perfekter kleiner Winkel', 'Dennis'),
  ('Springpferd', 'Dennis'),
  ('El Kröterich', 'Dennis'),
  ('Trüffelnase', 'Dennis'),
  ('Mausezahn', 'Dennis'),
  ('Eierkopf', 'Dennis'),
  ('Zwiebelhexe', 'Dennis'),
  ('Eiertanzbär', 'Dennis'),
  ('Knödelmaus', 'Dennis'),
  ('Kanalratte', 'Dennis'),
  ('Hohle Fritte', 'Dennis'),
  ('Schneckeroncinii', 'Dennis');

-- Ausschleichplan Alprazolam (Dr. Feist, 28.09.2026) – Tag 1 = 03.10.2026
insert into meds (name, kind, times, note, taper, author) values
  ('Alprazolam', 'taper', '{}', 'Auffälligkeiten sofort Dr. Feist melden',
   '{"start": "2026-10-03", "pre": {"mg": 0.5, "pieces": "1 Tbl. 0,5 mg"}, "steps": [{"days": 10, "mg": 0.4375, "pieces": "¾ Tbl. 0,5 mg + ¼ Tbl. 0,25 mg"}, {"days": 10, "mg": 0.375, "pieces": "¾ Tbl. 0,5 mg"}, {"days": 10, "mg": 0.3125, "pieces": "½ Tbl. 0,5 mg + ¼ Tbl. 0,25 mg"}, {"days": 14, "mg": 0.25, "pieces": "½ Tbl. 0,5 mg"}, {"days": 14, "mg": 0.1875, "pieces": "¼ Tbl. 0,5 mg + ¼ Tbl. 0,25 mg"}, {"days": 14, "mg": 0.125, "pieces": "¼ Tbl. 0,5 mg"}, {"days": 14, "mg": 0.0625, "pieces": "¼ Tbl. 0,25 mg"}]}'::jsonb, 'Dennis');
